generalInformation:
  serviceAdminEmail: a
  gheUsername: kkanto
  billingAccount: a
  billingTeamName: a
  gheToken: ""
  adpAccessToken: ""
jira:
  adminToken: ""
  projectKey: a
  projectName: a
  leadUsername: a
  documentationUrl: a
projectInformation:
  projectName: TestProjectNameMaven1231232132
  projectShortName: asdasdasd2
  buildType: maven
  testInstance: false
  preprodInstance: false
  uatInstance: false
cloudService:
  awsOrAzure: aks
  deploymentLocation: azure_we1
automationService:
  jenkinsOrGithubActions: gheactions
  jenkinsAdmin: ""
  jenkinsDeveloper: ""
  jenkinsKubernetesAccess: ""
  kvUserOrGroupName: ""
  nexusKubernetesAccess: a
gheOrganization:
  organizationName: kkanto
  isNew: false
testingTools:
  sonarQube: false
  adminGroup: ""
  kubernetesAccess: ""
